### ISSUE TITLE
RTS Units don't attack very well the base (online)

### ISSUE THREAD

**Issue by fermonas** [maxi-jp/Project_NewDetroit#57]
Playing online mode, units doesn't attack very well the enemy base. They do strange things.

**Comment by DiegoGal** [comment]
Need more information of the "strange things"

**Comment by fermonas** [comment]
You told me to write this "strange things"...
What a Gallu...poor Gallu...

**Comment by fermonas** [comment]
I can not reproduce the issue. It seems to work well.
