### ISSUE TITLE
Tower Colliders too high?

### ISSUE THREAD

**Issue by fermonas** [maxi-jp/Project_NewDetroit#71]
We have to look at the colliders of the towers, because if you send an engineer to repair the tower and you select at the top of the tower he won't go to repair it.

Maybe it is because the collider is too high.

**Comment by fermonas** [comment]
It is not because of the colliders. When you click on the top of a tower the y coordinate of destiny poiint is 6.0f. I am going to modify this point to 3.0f (ñap)

**Comment by maxi-jp** [comment]
ñaper & commander

**Comment by fermonas** [comment]
LOL
